language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - gcc
    - g++
    - clang

# command to run tests
script: 
  - git submodule update --init
  - python setup.py build
  - mkdir build
  - cd build
  - cmake .. -DCEGO_ALL=ON -DCEGO_NO_PYTHON=ON -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - ./StornPriceprofiling
  - ./main
  - ./shaped_inverse_gaussian

notifications:
  email:
    recipients:
      - ian.bell@nist.gov
    on_success: never # default: change
    on_failure: always # default: always
